---
# - hosts: 127.0.0.1
#   connection: local
#   tasks:
#     - debug: msg="Check that we are running in the directory of the script."
#       failed_when: not ansible_env.PWD.endswith('/ansible-dev-setup')


- hosts: 127.0.0.1
  connection: local
  tasks:
    - include_role:
        name: local_common
