---

- name: Re-map CAPS LOCK to CTRL.
  shell: setxkbmap us -variant dvorak -option ctrl:nocaps

- name: Make DropBox autostart.
  shell: dropbox autostart y

- name: Set shell to zsh.
  shell: chsh -S /bin/zsh
