---
- name: Install VS Code.
  become_user: root
  become: yes
  dnf:
    name: code
    state: latest

- name: Install dnf packages.
  become_user: root
  become: yes
  dnf:
    name: '{{ item }}'
  with_items: '{{ dnf_packages }}'
  tags: dnf


# ripgrep is a COPR project with no ansible dnf support.
- name: Add COPR repo for ripgrep.
  command: dnf copr enable carlwgeorge/ripgrep -y
  become: yes
  become_user: root

- name: Install ripgrep from its COPR repository.
  command: dnf install ripgrep -y
  become: yes
  become_user: root