---
- name: Add Microsoft VS Code repository key.
  become_user: root
  become: yes
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  
- name: Use Microsoft VS Code repository.
  become_user: root
  become: yes
  shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install VS Code.
  become_user: root
  become: yes
  dnf:
    name: code
    state: latest

- name: Install dnf packages.
  become_user: root
  become: yes
  dnf:
    name: '{{ item }}'
  with_items: '{{ dnf_packages }}'
  tags: dnf


# ripgrep is a COPR project with no ansible dnf support.
- name: Add COPR repo for ripgrep.
  command: dnf copr enable carlwgeorge/ripgrep -y
  become: yes
  become_user: root

- name: Install ripgrep from its COPR repository.
  command: dnf install ripgrep -y
  become: yes
  become_user: root