---
- name: Install dotfiles
  copy: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - { src: "dotfiles/spacemacs", dest: "~/.spacemacs" }
    - { src: "dotfiles/vimrc", dest: "~/.vimrc" }

