---
homebrew_taps:
  - caskroom/cask
  - caskroom/fonts

homebrew_packages:
  - certbot
  - ffmpeg
  - gawk
  - git
  - gpg
  - htop
  - imagemagick
  - jq
  - node
  - parallel
  - terraform
  - tmux
  - watch
  - xz

homebrew_cask_packages:
  - anki
  - calibre
  - dash
  - docker
  - dropbox
  - emacs
  - firefox
  - google-chrome
  - iterm2
  - java
  - skype
  - slack
  - spotify
  - virtualbox
  - visual-studio-code
  - vlc
  - wireshark 
